trigger:
- master

schedules:
- cron: "30 23 * * *"
  displayName: "Daily 5 AM IST Test Run"
  branches:
    include:
    - master
  always: true # Ensures the pipeline runs even if there are no code changes

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Selenium Tests'
  inputs:
    command: 'test'
    projects: 'SpecFlowBDDTest/SpecFlowBDDTest.csproj'